<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8468" started-at="2018-05-28T16:58:23Z" finished-at="2018-05-28T16:58:32Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="8468" started-at="2018-05-28T16:58:23Z" finished-at="2018-05-28T16:58:32Z">
      <class name="com.qa.testcases.WeatherInfoTest">
        <test-method status="FAIL" signature="getWeatherDetailswithCity(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.qa.testcases.WeatherInfoTest@7c16905e]" name="getWeatherDetailswithCity" duration-ms="5720" started-at="2018-05-28T22:28:24Z" data-provider="getData" finished-at="2018-05-28T22:28:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Rourkela]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[get]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[28.649 Degree celsius]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[77 Percent]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[0.51 Km per hour]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[271.002 Degree]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [77 Percent] but found [79 Percent]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [77 Percent] but found [79 Percent]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:179)
	at com.qa.testcases.WeatherInfoTest.getWeatherDetailswithCity(WeatherInfoTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getWeatherDetailswithCity -->
        <test-method status="FAIL" signature="getWeatherDetailswithCity(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.qa.testcases.WeatherInfoTest@7c16905e]" name="getWeatherDetailswithCity" duration-ms="1673" started-at="2018-05-28T22:28:30Z" data-provider="getData" finished-at="2018-05-28T22:28:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Sundargarh]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[get]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[26.099 Degree celsius]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[82 Percent]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[0.96 Km per hour]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[177.502 Degree]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [82 Percent] but found [80 Percent]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [82 Percent] but found [80 Percent]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:179)
	at com.qa.testcases.WeatherInfoTest.getWeatherDetailswithCity(WeatherInfoTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getWeatherDetailswithCity -->
      </class> <!-- com.qa.testcases.WeatherInfoTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
